export const ARTICLES = [
  {
    id: "a01", topic: "basics",
    titleFa: "بلاک‌چین چیست؟",
    titleEn: "What is Blockchain?",
    bodyFa: "بلاک‌چین یک دفترکل دیجیتال است که اطلاعات (تراکنش‌ها) را در قالب «بلاک»هایی که به هم زنجیر شده‌اند ثبت می‌کند. هر بلاک حاوی خلاصه ریاضی بلاک قبلی است؛ بنابراین اگر کسی بخواهد یک بلاک را تغییر دهد، باید همه بلاک‌های بعدی را هم بازنویسی کند که عملاً غیرممکن و بسیار پرهزینه است. به همین دلیل به بلاک‌چین «تغییرناپذیر» می‌گویند.\n\nبلاک‌چین غیرمتمرکز است: نسخه‌ای از دفترکل روی هزاران رایانه (گره) در سراسر جهان نگهداری می‌شود و هیچ بانک یا دولتی آن را کنترل نمی‌کند. اعتماد نه به یک شخص، بلکه به قواعد ریاضی است.\n\nبیت‌کوین اولین کاربرد بلاک‌چین بود، اما امروزه بلاک‌چین‌های عمومی مانند Polygon امکان ساخت قراردادهای هوشمند و توکن‌های دلخواه را هم فراهم کرده‌اند. بلاک‌چین می‌تواند در امور مالی، زنجیره تأمین، رأی‌گیری و ثبت اسناد به کار رود.\n\nنکته اسلامی: بلاک‌چین خود یک ابزار است؛ حلال یا حرام بودن آن به کاربردش بستگی دارد. هرچه با ربا، قمار یا فریب همراه باشد حرام است و آنچه شفاف و بر پایه کار و تلاش واقعی باشد مجاز است.",
    bodyEn: "Blockchain is a digital ledger that records information (transactions) in \"blocks\" chained together. Each block contains a mathematical digest of the previous block, so altering one block would require rewriting every following block — practically impossible and extremely costly. That is why blockchain is called \"immutable.\"\n\nBlockchain is decentralized: a copy of the ledger lives on thousands of computers (nodes) worldwide, controlled by no single bank or government. Trust rests on mathematical rules rather than any person or institution.\n\nBitcoin was the first use of blockchain, but public blockchains such as Polygon now also enable smart contracts and custom tokens. Blockchain can serve finance, supply chains, voting, and document registration.\n\nAn Islamic note: blockchain is a neutral tool; what makes it halal or haram is its use. Anything involving riba, gambling, or deception is forbidden, while transparent use built on real work and effort is permissible."
  },
  {
    id: "a02", topic: "basics",
    titleFa: "کیف پول ارز دیجیتال چیست؟",
    titleEn: "What is a Crypto Wallet?",
    bodyFa: "کیف پول ارز دیجیتال ابزاری است که کلیدهای خصوصی شما را نگه می‌دارد. در دنیای بلاک‌چین، دارایی شما واقعاً «در» کیف پول نیست؛ بلکه روی شبکه ثبت شده و کلید خصوصی فقط به شما اجازه می‌دهد آن را مدیریت کنید. هرکس کلید خصوصی یا عبارت بازیابی را داشته باشد، کنترل کامل دارایی را در دست دارد.\n\nکیف پول‌ها دو نوع‌اند: گرم (متصل به اینترنت، مثل افزونه مرورگر و اپ موبایل) و سرد (آفلاین، مثل دستگاه‌های سخت‌افزاری). کیف پول گرم برای استفاده روزمره راحت است و کیف پول سرد برای نگهداری بلندمدت امن‌تر است.\n\nهنگام ساخت کیف پول، یک عبارت بازیابی ۱۲ یا ۲۴ کلمه‌ای دریافت می‌کنید. این عبارت مهم‌ترین دارایی شماست؛ اگر گم شود، دارایی برای همیشه از دست می‌رود و هیچ کس نمی‌تواند آن را برگرداند.\n\nنکته امنیتی: عبارت بازیابی را هرگز آنلاین ذخیره نکنید، عکس نگیرید و در پیام‌رسان نفرستید. آن را روی کاغذ بنویسید و در جای امن آفلاین نگهداری کنید. صرافی‌ها و سایت‌های معتبر هرگز از شما عبارت بازیابی نمی‌خواهند.",
    bodyEn: "A crypto wallet is a tool that stores your private keys. On a blockchain, your assets are not really \"in\" the wallet; they are recorded on the network, and the private key simply lets you manage them. Whoever holds the private key or recovery phrase has full control of the funds.\n\nWallets come in two types: hot wallets (connected to the internet, such as browser extensions and mobile apps) and cold wallets (offline, such as hardware devices). Hot wallets are convenient for daily use; cold wallets are safer for long-term storage.\n\nWhen you create a wallet you receive a 12- or 24-word recovery phrase. That phrase is your most important asset; if you lose it, the funds are gone forever and no one can restore them.\n\nSecurity note: never store your recovery phrase online, never photograph it, and never send it through messengers. Write it on paper and keep it safe offline. Legitimate exchanges and sites will never ask for your recovery phrase."
  },
  {
    id: "a03", topic: "basics",
    titleFa: "قرارداد هوشمند چیست؟",
    titleEn: "What are Smart Contracts?",
    bodyFa: "قرارداد هوشمند یک برنامه رایانه‌ای است که روی بلاک‌چین اجرا می‌شود و وقتی شرایطی فراهم شود، به‌صورت خودکار عمل می‌کند. مثلاً یک قرارداد می‌تواند تعیین کند: اگر پرداخت انجام شد، توکن به خریدار تحویل داده شود. هیچ واسطه‌ای برای اجرا لازم نیست؛ کد خودش اجرا می‌شود.\n\nمزیت اصلی قراردادهای هوشمند شفافیت است: کد آن برای همه قابل مشاهده است و پس از انتشار قابل تغییر نیست. این یعنی هیچ طرفی نمی‌تواند بعداً شرایط را عوض کند.\n\nروی شبکه Polygon هزاران قرارداد هوشمند فعال است؛ از جمله قراردادهای سازنده توکن (Factory) که با آن می‌توان توکن ERC-20 جدید ساخت. وقتی شما در PolyMint توکن می‌سازید، در واقع یک قرارداد هوشمند اجرا می‌کنید که خروجی آن یک توکن جدید روی بلاک‌چین است.\n\nنکته: چون قراردادها پس از انتشار تغییرناپذیرند، کد قراردادهایی که استفاده می‌کنید را حتماً از منبع معتبر بررسی کنید. در محیط‌های اسلامی، قرارداد باید عاری از ربا، قمار و ابهام (غرر) باشد.",
    bodyEn: "A smart contract is a computer program that runs on a blockchain and acts automatically when certain conditions are met. For example, a contract can state: if payment is received, deliver the token to the buyer. No intermediary is needed; the code executes itself.\n\nThe main advantage of smart contracts is transparency: the code is visible to everyone and, once published, cannot be changed. No party can later alter the terms.\n\nThousands of smart contracts run on the Polygon network, including token factory contracts that create new ERC-20 tokens. When you create a token on PolyMint, you are executing a smart contract whose output is a brand-new token on the blockchain.\n\nNote: because contracts are immutable once published, always verify the code of any contract you use from a trusted source. In Islamic settings, a contract must be free of riba, gambling, and ambiguity (gharar)."
  },
  {
    id: "a04", topic: "basics",
    titleFa: "توکن ERC-20 چیست؟",
    titleEn: "What is an ERC-20 Token?",
    bodyFa: "ERC-20 یک استاندارد فنی برای توکن‌های روی شبکه اتریوم و شبکه‌های سازگار مثل Polygon است. این استاندارد تعیین می‌کند که یک توکن چه توابعی داشته باشد: نام، نماد، تعداد ارقام اعشار، انتقال، استعلام موجودی و... . به همین دلیل همه کیف پول‌ها و صرافی‌ها می‌توانند هر توکن ERC-20 را به‌راحتی نمایش دهند.\n\nوقتی در PolyMint توکن می‌سازید، توکن شما طبق همین استاندارد منتشر می‌شود؛ یعنی با تمام کیف پول‌های استاندارد، صرافی‌های غیرمتمرکز و ابزارهای تحلیل سازگار است.\n\nنکته مهم: عرضه و مشخصات توکن پس از ساخت در بلاک‌چین ثبت می‌شود و قابل تغییر نیست. بنابراین قبل از ساخت، نام، نماد و عرضه را با دقت بررسی کنید.\n\nاز منظر اسلامی، توکن به‌خودی‌خود حلال یا حرام نیست؛ ارزش و استفاده از آن تعیین‌کننده است. توکنی که پشت آن کار، دارایی یا خدمت واقعی باشد از توکنی که صرفاً ابزار سوداگری و ریسک است، پایدارتر و از نظر فقهی مطمئن‌تر است.",
    bodyEn: "ERC-20 is a technical standard for tokens on the Ethereum network and compatible networks such as Polygon. It defines what functions a token must have: name, symbol, number of decimals, transfer, balance inquiry, and more. This is why every wallet and exchange can display any ERC-20 token easily.\n\nWhen you create a token on PolyMint, it is issued according to this same standard — compatible with all standard wallets, decentralized exchanges, and analytics tools.\n\nImportant: the supply and details of a token are recorded on the blockchain after creation and cannot be changed. So double-check the name, symbol, and supply before creating it.\n\nFrom an Islamic perspective, a token is not halal or haram by itself; its value and use decide. A token backed by real work, assets, or services is more stable and more reliable from a fiqh standpoint than one used purely for speculation and risk."
  },
  {
    id: "a05", topic: "basics",
    titleFa: "رمزنگاری چگونه امنیت می‌سازد؟",
    titleEn: "How Does Cryptography Provide Security?",
    bodyFa: "امنیت بلاک‌چین بر دو ابزار ریاضی استوار است: تابع هش و جفت‌کلید (کلید عمومی/خصوصی). تابع هش هر داده‌ای را به یک اثر انگشت دیجیتال کوتاه تبدیل می‌کند؛ حتی تغییر یک حرف، خروجی را کاملاً عوض می‌کند. به این ترتیب هر تغییری در بلاک‌ها بلافاصله آشکار می‌شود.\n\nجفت‌کلیدها به این شکل کار می‌کنند: کلید عمومی آدرس شماست که برای دریافت دارایی به دیگران می‌دهید؛ کلید خصوصی فقط برای شماست و برای امضای تراکنش لازم است. امضا ریاضی نشان می‌دهد که صاحب کلید خصوصی واقعاً آن تراکنش را تأیید کرده است، بدون اینکه نیاز به افشای کلید باشد.\n\nاین طراحی به ما امکان می‌دهد دارایی را «بلااعتماد» نگهداری کنیم: نه به بانک نیاز داریم و نه باید به کسی اعتماد کنیم؛ امنیت از ریاضیات می‌آید.\n\nنکته: قوی‌ترین رمزنگاری هم اگر کاربر بی‌احتیاط باشد بی‌فایده است. کلید خصوصی و عبارت بازیابی را امن نگه دارید؛ آن‌ها تنها نقطه ضعف احتمالی شما هستند.",
    bodyEn: "Blockchain security rests on two mathematical tools: hash functions and key pairs (public/private). A hash function turns any data into a short digital fingerprint; even changing a single letter completely changes the output. This makes any change in blocks immediately detectable.\n\nKey pairs work like this: the public key is your address, which you give to others to receive funds; the private key is for you alone and is needed to sign transactions. A signature mathematically proves that the owner of the private key authorized that transaction, without ever revealing the key.\n\nThis design lets us hold assets \"trustlessly\": no bank is needed, and no one must be trusted; security comes from mathematics.\n\nNote: even the strongest cryptography is useless if the user is careless. Keep your private key and recovery phrase secure; they are your only possible weak point."
  },
  {
    id: "a06", topic: "basics",
    titleFa: "سکه و توکن چه فرقی دارند؟",
    titleEn: "Coins vs Tokens: What's the Difference?",
    bodyFa: "«سکه» (Coin) ارز دیجیتال اصلی یک بلاک‌چین است که روی شبکه خودش اجرا می‌شود؛ مثل بیت‌کوین یا پول Polygon (POL). سکه معمولاً برای پرداخت کارمزد تراکنش و به عنوان پول شبکه استفاده می‌شود.\n\n«توکن» (Token) روی یک بلاک‌چین دیگر ساخته می‌شود؛ یعنی بر پایه قرارداد هوشمند یک شبکه میزبان. توکن‌های ERC-20 روی اتریوم یا Polygon از این دسته‌اند. توکن می‌تواند نماینده یک دارایی، حق استفاده از یک خدمت یا واحد یک پروژه باشد.\n\nدر PolyMint شما توکن می‌سازید، نه سکه. یعنی توکن شما روی شبکه Polygon زندگی می‌کند و از امنیت و زیرساخت آن بهره می‌برد؛ بدون اینکه نیاز به راه‌اندازی یک بلاک‌چین جداگانه باشد.\n\nدرک این تفاوت مهم است چون از نظر فقهی هم تفاوت دارد: سکه شبکه وسیله پرداخت است، اما توکن باید نماینده ارزش واقعی و شفاف باشد. توکنی که ارزش آن بر پایه کار، تولید یا دارایی حقیقی باشد، از نظر اقتصادی و شرعی سالم‌تر است.",
    bodyEn: "A \"coin\" is the native digital currency of a blockchain, running on its own network — like Bitcoin or Polygon's POL. Coins are typically used to pay transaction fees and as the network's money.\n\nA \"token\" is built on top of another blockchain, based on a smart contract on a host network. ERC-20 tokens on Ethereum or Polygon belong to this category. A token can represent an asset, access to a service, or a unit of a project.\n\nOn PolyMint you create tokens, not coins. Your token lives on the Polygon network and benefits from its security and infrastructure — no need to run a separate blockchain.\n\nUnderstanding this difference matters because it also matters from a fiqh perspective: a network coin is a means of payment, while a token should represent real, transparent value. A token whose value rests on real work, production, or genuine assets is economically and Islamically sounder."
  },
  {
    id: "a07", topic: "islamic",
    titleFa: "نگاه فقهی به رمزارزها",
    titleEn: "Islamic Scholars' View on Crypto",
    bodyFa: "نگاه علما به رمزارزها یک‌دست نیست و در چند دسته قرار می‌گیرد. برخی رمزارز را با توجه به ویژگی‌های پول (واحد شمارش، وسیله مبادله، ذخیره ارزش) جایز می‌دانند، برخی آن را به دلیل سوداگری شدید و ریسک نامتعارف مکروه یا حرام می‌دانند، و برخی نظر به استفاده آن دارند؛ یعنی بسته به کاربرد، حکم متفاوت می‌شود.\n\nنکته مهم این است که اصل در معاملات، حلال بودن است مگر اینکه عنصر حرام اثبات شود. عناصری مثل ربا (سود ثابت وام)، قمار (شرط‌بندی بر نتیجه تصادفی) و غرر (ابهام بیش از حد) معامله را حرام می‌کنند.\n\nبنابراین فعالیت‌هایی که بر پایه کار و تلاش واقعی باشند — مثل تولید محتوا، توسعه نرم‌افزار، ماینینگ، فروش کالا و خدمات در ازای رمزارز — معمولاً جایز شمرده می‌شوند. در مقابل، هر کاری که ماهیت شرط‌بندی یا بهره داشته باشد مشکل‌دار است.\n\nپیشنهاد: قبل از هر تصمیم مالی مهم، با یک عالم یا نهاد فقهی معتبر در کشور خود مشورت کنید و از فعالیت‌های دارای ربا، قمار یا ابهام شدید پرهیز کنید.",
    bodyEn: "Scholars' views on cryptocurrencies are not uniform and fall into several camps. Some regard crypto as permissible given its money-like features (unit of account, medium of exchange, store of value); some consider it makruh or haram because of intense speculation and disproportionate risk; and some hold a use-based view, judging it by how it is used.\n\nAn important principle is that the default ruling on transactions is permissibility unless a forbidden element is proven. Elements such as riba (fixed interest on loans), gambling (betting on random outcomes), and excessive gharar (ambiguity) make a transaction haram.\n\nTherefore activities based on real work and effort — such as content creation, software development, mining, and selling goods and services for crypto — are generally considered permissible. In contrast, anything that is essentially betting or interest-based is problematic.\n\nAdvice: before any major financial decision, consult a trustworthy scholar or fiqh institution in your country, and avoid activities involving riba, gambling, or excessive ambiguity."
  },
  {
    id: "a08", topic: "islamic",
    titleFa: "زکات رمزارز چگونه محاسبه می‌شود؟",
    titleEn: "How to Calculate Zakat on Crypto",
    bodyFa: "زکات بر دارایی‌هایی واجب است که به حد نصاب برسند و یک سال (قمری) از مالکیت آن‌ها گذشته باشد. درباره رمزارز، نظر رایج میان علما و نهادهای زکات این است که اگر رمزارز به عنوان دارایی سرمایه‌ای نگهداری شود، زکات آن مانند طلا و نقره (۲.۵٪) یا مانند سهم و سهام (۱۰٪ یا ۲.۵٪ بسته به فتوا) محاسبه می‌شود. بسیاری از نهادهای فقهی معاصر، نرخ ۲.۵٪ را برای رمزارز توصیه کرده‌اند.\n\nبرای محاسبه: ارزش کل رمزارز خود را به ارز محلی تبدیل کنید. اگر این ارزش در روز محاسبه از نصاب (مثلاً معادل ۸۵ گرم طلا) بیشتر بود و یک سال قمری از نگهداری گذشته بود، ۲.۵٪ آن را زکات بدهید.\n\nبرای اطمینان، تاریخ دریافت، مقدار و ارزش هر دارایی را ثبت کنید تا محاسبه درست انجام شود.\n\nنکته: اگر رمزارز را برای مبادله روزمره نگه می‌دارید، نظر برخی علما این است که باید زکات نقدینگی (۲.۵٪) پرداخت شود. در هر صورت بهتر است با نهاد زکات کشور خود هماهنگ کنید.",
    bodyEn: "Zakat is obligatory on wealth that reaches the nisab threshold and has been owned for one (lunar) year. Regarding crypto, the common view among scholars and zakat institutions is that if crypto is held as an investment asset, its zakat is calculated like gold and silver (2.5%) or like shares (10% or 2.5% depending on the fatwa). Many contemporary fiqh bodies recommend the 2.5% rate for crypto.\n\nTo calculate: convert your total crypto holdings into your local currency. If this value on the calculation day exceeds the nisab (for example, the equivalent of 85 grams of gold) and one lunar year of ownership has passed, pay 2.5% of it as zakat.\n\nFor accuracy, record the date of receipt, quantity, and value of each holding.\n\nNote: if you hold crypto for everyday exchange, some scholars hold that zakat on liquid money (2.5%) must be paid. In all cases, it is best to coordinate with your country's official zakat institution."
  },
  {
    id: "a09", topic: "islamic",
    titleFa: "ربا چیست و چرا باید از آن پرهیز کرد؟",
    titleEn: "What is Riba and Why Must We Avoid It?",
    bodyFa: "ربا به زبان ساده، سود یا افزایشی است که در مقابل اصل وام یا بدهی گرفته می‌شود. در قرآن به‌صراحت از ربا نهی شده و در کنار آن توصیه به «تجارت» (دادوستد حلال بر پایه کالا و کار واقعی) شده است. ربا باعث می‌شود پول بدون تلاش و بدون تحمل ریسک، رشد کند و ثروت از طبقات محروم به ثروتمندان منتقل شود.\n\nدر دنیای کریپتو، ربا به شکل‌های مختلف ظاهر می‌شود:\n• وام‌دهی رمزارز (Lending) با سود ثابت\n• استیکینگ با بازده تضمینی که ماهیت بهره‌ای دارد\n• «حساب‌های سودده» صرافی‌ها که سپرده را با سود برگردانند\n\nاین موارد معمولاً در دسته ربا یا شبهه‌ی ربا قرار می‌گیرند و از نظر فقهی مشکل‌دارند.\n\nروش حلال کسب درآمد: کار و تولید واقعی، ارائه خدمت، فروش کالا، سرمایه‌گذاری مشترک با تقسیم سود و زیان (مضاربه و مشارکت) به جای وام با سود ثابت. اگر درآمدی از راه‌های حرام یا مشکوک به دست آورده‌اید، بهتر است آن را کنار بگذارید و از آن صرف‌نظر کنید یا به فقرا بدهید و فعالیت حلال را جایگزین کنید.",
    bodyEn: "Riba, simply put, is interest or any increase charged in return for the principal of a loan or debt. The Quran explicitly forbids riba and, alongside it, recommends \"trade\" (halal exchange based on real goods and work). Riba lets money grow without effort and without bearing risk, shifting wealth from the deprived to the rich.\n\nIn the crypto world, riba appears in several forms:\n• Crypto lending with fixed interest\n• Staking with guaranteed yields that are interest-like\n• Exchanges' \"interest accounts\" that pay returns on deposits\n\nThese are generally categorized as riba or riba-adjacent and are problematic from a fiqh standpoint.\n\nHalal ways to earn: real work and production, providing services, selling goods, and joint investment with profit-and-loss sharing (mudarabah and musharakah) instead of fixed-interest loans. If you have earned through haram or doubtful means, it is better to set it aside, give it away to the poor, and replace it with a halal activity."
  },
  {
    id: "a10", topic: "islamic",
    titleFa: "آیا ماینینگ حلال است؟",
    titleEn: "Is Mining Halal?",
    bodyFa: "ماینینگ (استخراج) فرایندی است که در آن رایانه‌ها با صرف برق و توان محاسباتی، تراکنش‌های بلاک‌چین را تأیید و بلاک جدید تولید می‌کنند و در ازای آن پاداش شبکه دریافت می‌کنند. ماهیت ماینینگ «کار و تلاش واقعی» است: ماینر با سرمایه‌گذاری و هزینه‌کردن، خدمتی به شبکه ارائه می‌دهد و ریسک (نوسان قیمت، خرابی تجهیزات، افزایش برق) را می‌پذیرد.\n\nبه همین دلیل بسیاری از علما ماینینگ را جایز می‌دانند، به شرطی که:\n۱. تجهیزات، برق و هزینه‌ها با منابع حلال تأمین شود\n۲. درآمد حاصل به‌صورت شفاف و بر پایه خدمت واقعی باشد\n۳. وارد کارهای ربا یا قمار نشود\n\nالبته برخی علما هم به دلیل مصرف انرژی و برخی ابهامات، نظر احتیاطی دارند. بنابراین حتماً نظر نهاد فقهی کشور خود را بپرسید.\n\nنکته عملی: قبل از ورود به ماینینگ، هزینه برق، استهلاک سخت‌افزار و نوسان قیمت ارز را به‌دقت محاسبه کنید. کار حلال و موفق، کاری است که اول با دانش و برنامه‌ریزی همراه باشد.",
    bodyEn: "Mining is the process in which computers, by consuming electricity and computing power, validate blockchain transactions and produce new blocks, receiving network rewards in return. The nature of mining is \"real work and effort\": a miner invests capital and effort, provides a service to the network, and bears risk (price volatility, hardware failure, rising electricity costs).\n\nFor this reason many scholars consider mining permissible, provided that:\n1. The equipment, electricity, and costs come from halal sources\n2. Income is transparent and based on genuine service\n3. It does not involve riba or gambling\n\nSome scholars, however, take a precautionary view due to energy consumption and certain ambiguities. So be sure to ask your country's fiqh institution.\n\nPractical note: before entering mining, carefully calculate electricity costs, hardware depreciation, and currency price volatility. Halal and successful work is work that starts with knowledge and planning."
  },
  {
    id: "a11", topic: "islamic",
    titleFa: "قمار (قیمر) در بازار رمزارز",
    titleEn: "Gambling (Qimar) in the Crypto Market",
    bodyFa: "اسلام قمار را حرام کرده است. قمار یعنی شرط‌بندی که در آن مال یکی از طرفین بدون کار و تلاش به دیگری منتقل شود و نتیجه به شانس و تصادف بستگی داشته باشد.\n\nدر بازار کریپتو، برخی فعالیت‌ها ماهیت قمار دارند:\n• ترید با اهرم بالا (Margin) که سود و زیان عظیم بدون پایه واقعی دارد\n• پیش‌بینی قیمت و شرط‌بندی روی صعود یا نزول (باینری آپشن‌ها)\n• پروژه‌های «به این زودی‌تر» (Pump and Dump) که عدّه‌ای را فریب می‌دهند\n• لاتاری‌ها و بخت‌آزمایی‌های توکنی\n\nاین فعالیت‌ها نه‌تنها از نظر شرعی مشکل دارند، از نظر اقتصادی هم معمولاً به ضرر اکثریت شرکت‌کنندگان تمام می‌شود.\n\nراه سالم: سرمایه‌گذاری بر پایه کار، تولید و دارایی واقعی؛ نگهداری بلندمدت دارایی‌های شناخته‌شده؛ و هرگز وارد کردن پولی که توان از دست دادن آن را ندارید. پولی که با عجله و طمع وارد بازار می‌شود، معمولاً با پشیمانی خارج می‌شود. از هر وعده «سود تضمینی» و «به‌سرعت ثروتمند شو» دوری کنید؛ در دنیای کریپتو هیچ سودی بدون ریسک تضمینی نیست.",
    bodyEn: "Islam forbids gambling. Gambling means betting in which the money of one party moves to another without work or effort, and the outcome depends on chance and randomness.\n\nIn the crypto market, some activities are gambling in nature:\n• High-leverage margin trading with enormous unreal gain or loss\n• Price prediction and betting on up or down moves (binary options)\n• \"Pump and dump\" schemes that deceive people\n• Token lotteries and lucky draws\n\nThese activities are not only problematic religiously but usually end in losses for the majority of participants economically.\n\nThe healthy path: invest based on work, production, and real assets; hold well-known assets long-term; and never put in money you cannot afford to lose. Money that enters the market with haste and greed usually exits with regret. Stay away from every promise of \"guaranteed profit\" and \"get rich fast\"; in crypto, no profit is guaranteed without risk."
  },
  {
    id: "a12", topic: "islamic",
    titleFa: "اقتصاد بدون بهره و عدالت مالی",
    titleEn: "Interest-Free Economy and Financial Justice",
    bodyFa: "اقتصاد اسلامی بر دو اصل بنا شده است: تجارت حلال (دادوستد بر پایه کالا، کار و خدمت واقعی) و نفی ربا (هرگونه افزایش بدون کار در مقابل وام). هدف این است که ثروت در جامعه بچرخد و فقط در دست ثروتمندان تجمع پیدا نکند.\n\nفناوری بلاک‌چین می‌تواند به این اهداف کمک کند:\n• شفافیت: همه تراکنش‌ها قابل مشاهده است و فساد و پنهان‌کاری سخت‌تر می‌شود\n• حذف واسطه‌های پرهزینه: انتقال مستقیم پول هزینه کمتری دارد\n• مالکیت واقعی: فرد بر دارایی خود کنترل کامل دارد\n\nبا این حال، فناوری خنثی است؛ درست مانند ابزارهای مالی سنتی، بلاک‌چین هم می‌تواند در خدمت عدالت یا در خدمت بهره‌کشی باشد. اگر در آن ربا، قمار و ابهام پیاده شود، مشکل شرعی همان‌طور پابرجاست.\n\nتأمل: وقتی توکن خود را می‌سازید یا از ارز دیجیتال استفاده می‌کنید، به این فکر کنید که فعالیت شما چه ارزش واقعی به جامعه می‌دهد. هرچه ارزش ایجاد کنید، هم کسب‌وکارتان پایدارتر است و هم از نظر شرعی سالم‌تر.",
    bodyEn: "The Islamic economy rests on two principles: halal trade (exchange based on real goods, work, and services) and the negation of riba (any increase without work in return for a loan). The goal is for wealth to circulate in society rather than accumulate in the hands of the rich.\n\nBlockchain technology can serve these goals:\n• Transparency: all transactions are visible, making corruption and concealment harder\n• Removing costly intermediaries: direct transfers cost less\n• Real ownership: the individual has full control over their assets\n\nYet technology is neutral; just like traditional financial tools, blockchain can serve justice or serve exploitation. If riba, gambling, and ambiguity are built into it, the religious problem remains the same.\n\nReflection: when you create your own token or use crypto, think about what real value your activity brings to society. The more value you create, the more sustainable your business and the sounder it is religiously."
  },
  {
    id: "a13", topic: "security",
    titleFa: "محافظت از عبارت بازیابی",
    titleEn: "Protecting Your Seed Phrase",
    bodyFa: "عبارت بازیابی (Seed Phrase) ۱۲ یا ۲۴ کلمه است که کلید کیف پول شما را بازسازی می‌کند. هر کس این عبارت را داشته باشد، می‌تواند دارایی شما را بدون هیچ تأییدی بردارد. مهم‌ترین قانون امنیت کریپتو همین است: «عبارت بازیابی، پول شماست».\n\nکارهای درست:\n• آن را روی کاغذ بنویسید و در دو یا سه نسخه در جاهای امن آفلاین نگهداری کنید\n• در گاوصندوق یا جایی که از آتش و آب در امان باشد قرار دهید\n• فقط در زمان بازسازی کیف پول (Restore) از آن استفاده کنید\n\nکارهای نادرست:\n• ذخیره در یادداشت گوشی، اسکرین‌شات، یا ایمیل\n• ارسال در پیام‌رسان‌ها (حتی برای پشتیبانی)\n• وارد کردن در سایت‌های ناشناس\n\nکلاهبرداران با وعده پشتیبانی، قرعه‌کشی یا به‌روزرسانی، سعی می‌کنند شما را فریب دهند تا عبارت را وارد کنید. به یاد داشته باشید: هیچ سایت و نهادی معتبری هرگز عبارت بازیابی شما را نمی‌خواهد. اگر کسی خواست، بدانید کلاهبردار است.",
    bodyEn: "The recovery phrase (Seed Phrase) is 12 or 24 words that reconstruct your wallet's keys. Whoever has this phrase can take your assets without any approval. The most important rule of crypto security is this: \"your recovery phrase is your money.\"\n\nRight things to do:\n• Write it on paper and keep two or three copies in secure offline places\n• Store it in a safe, protected from fire and water\n• Use it only when restoring a wallet\n\nWrong things to do:\n• Saving it in phone notes, screenshots, or email\n• Sending it through messengers (even to \"support\")\n• Entering it on unknown websites\n\nScammers use promises of support, lotteries, or updates to trick you into entering your phrase. Remember: no legitimate site or institution will ever ask for your recovery phrase. If anyone asks, they are a scammer."
  },
  {
    id: "a14", topic: "security",
    titleFa: "کلاهبرداری‌های رایج در کریپتو",
    titleEn: "Common Crypto Scams",
    bodyFa: "هرچقدر بازار کریپتو بزرگ‌تر می‌شود، کلاهبرداری‌ها هم متنوع‌تر می‌شوند. آشنایی با رایج‌ترین شگردها، بهترین سپر دفاعی شماست:\n\n۱. فیشینگ: سایت یا پیام جعلی که شبیه سایت واقعی است تا عبارت بازیابی یا کلید شما را بدزدد.\n۲. باج‌گیری/پشتیبانی دروغین: پیام‌هایی که ادعا می‌کنند از طرف تیم هستند و «کمک» می‌خواهند.\n۳. هدیه و اهدا: «برای هر کسی که X بفرستد، دوبرابر برمی‌گردد» — این همیشه کلاهبرداری است.\n۴. پروژه‌های جعلی (Rug Pull): توکنی که تبلیغ زیادی می‌شود و بعد سازندگان نقدینگی را برمی‌دارند و فرار می‌کنند.\n۵. سرمایه‌گذاری با سود تضمینی و عجیب: هیچ سود تضمینی در کریپتو وجود ندارد.\n۶. «تحلیلگران» و «مدیران» ادعایی در شبکه‌های اجتماعی که پول شما را «مدیریت» می‌کنند.\n\nقانون طلایی: هر پیشنهادی که «باید عجله کنی» یا «سود تضمینی» بدهد، کلاهبرداری است. قبل از هر سرمایه‌گذاری، چند روز صبر کنید، پروژه را از چند منبع مستقل بررسی کنید و با افراد آگاه مشورت کنید.",
    bodyEn: "As the crypto market grows, scams become more diverse. Knowing the most common tricks is your best defense:\n\n1. Phishing: fake sites or messages mimicking real ones to steal your recovery phrase or keys.\n2. Fake support/extortion: messages claiming to be from the team offering \"help.\"\n3. Giveaways: \"send X and get double back\" — this is always a scam.\n4. Fake projects (rug pulls): tokens heavily promoted, then creators remove liquidity and flee.\n5. Investments with guaranteed, unreal profits: no guaranteed profit exists in crypto.\n6. Self-proclaimed \"analysts\" and \"managers\" on social media who will \"manage\" your money.\n\nThe golden rule: any offer that says \"hurry up\" or promises \"guaranteed profit\" is a scam. Before any investment, wait a few days, verify the project from several independent sources, and consult knowledgeable people."
  },
  {
    id: "a15", topic: "security",
    titleFa: "فیشینگ چیست و چگونه از آن دور بمانیم؟",
    titleEn: "What is Phishing and How to Avoid It?",
    bodyFa: "فیشینگ روشی است که در آن کلاهبردار با ساخت سایت، پیام یا ایمیل جعلی، شما را فریب می‌دهد تا اطلاعات حساس (عبارت بازیابی، کلید خصوصی، رمز عبور) را وارد کنید. سایت جعلی معمولاً دقیقاً شبیه سایت واقعی است و یک تفاوت کوچک در آدرس دارد.\n\nراه‌های محافظت:\n• همیشه آدرس سایت را خودتان تایپ کنید یا از بوکمارک استفاده کنید؛ نه از لینک داخل پیام\n• قبل از وارد کردن اطلاعات، دامنه را در نوار آدرس با دقت بررسی کنید\n• سایت‌های مهم را با داشتن قفل امنیتی (HTTPS) اما نه فقط به آن تکیه کنید\n• اگر پیامی می‌گوید «کیف پول شما بسته می‌شود» یا «جایزه بردی»، حتماً فریب است\n• از افزونه‌های مسدودکننده تبلیغات و بررسی امضای قراردادهای هوشمند استفاده کنید\n\nمثال واقعی: پیامی از «صرافی» که از شما می‌خواهد با کلیک روی لینک، «تأیید هویت» کنید. صرافی‌ها چنین پیامی هرگز نمی‌فرستند. همیشه پیام‌های حساس را از راه رسمی (خود وب‌سایت) بررسی کنید.",
    bodyEn: "Phishing is a method in which scammers build fake sites, messages, or emails that mimic real ones to trick you into entering sensitive information (recovery phrase, private key, password). The fake site usually looks exactly like the real one with a tiny difference in the address.\n\nWays to protect yourself:\n• Always type the site address yourself or use a bookmark, never a link from a message\n• Before entering any information, carefully check the domain in the address bar\n• Prefer sites with HTTPS, but do not rely on the padlock alone\n• If a message says \"your wallet will be locked\" or \"you won a prize,\" it is definitely a trick\n• Use ad-blockers and tools that verify smart contract signatures\n\nReal example: a message from an \"exchange\" asking you to click a link to \"verify identity.\" Exchanges never send such messages. Always verify sensitive messages through the official route (the website itself)."
  },
  {
    id: "a16", topic: "security",
    titleFa: "کیف پول سرد در برابر کیف پول گرم",
    titleEn: "Cold vs Hot Wallets",
    bodyFa: "کیف پول گرم (Hot) به اینترنت متصل است؛ مثل افزونه مرورگر، اپ موبایل و کیف پول‌های داخل صرافی. مزیت آن راحتی و سرعت است: هر زمان خواستید می‌توانید انتقال دهید. عیب آن این است که در معرض حملات آنلاین (فیشینگ، بدافزار، هک سایت) قرار دارد.\n\nکیف پول سرد (Cold) به اینترنت متصل نیست؛ مثل دستگاه‌های سخت‌افزاری (Ledger، Trezor) یا کیف پول کاغذی. کلید خصوصی آن در محیط آفلاین نگهداری می‌شود و حتی اگر رایانه شما هک شود، دارایی در امان است. عیب آن ناراحتی استفاده برای تراکنش‌های روزمره است.\n\nراهبرد پیشنهادی:\n• مبلغی که برای استفاده روزمره نیاز دارید را در کیف پول گرم نگه دارید\n• سرمایه بلندمدت را در کیف پول سرد ذخیره کنید\n• هرگز مبلغ زیادی را در صرافی نگه ندارید؛ «کلیدهای شما نیست، مال شما نیست»\n\nنکته: در دستگاه سخت‌افزاری، عبارت بازیابی را فقط خودتان ثبت کنید. دستگاه را از منابع رسمی و بسته بخرید، نه دست دوم از فروشنده‌های ناشناس.",
    bodyEn: "A hot wallet is connected to the internet — browser extensions, mobile apps, and exchange wallets. Its advantage is convenience and speed: you can transfer anytime. Its downside is exposure to online attacks (phishing, malware, site hacks).\n\nA cold wallet is not connected to the internet — hardware devices (Ledger, Trezor) or paper wallets. The private key stays in an offline environment, so even if your computer is hacked, the funds remain safe. Its downside is inconvenience for daily transactions.\n\nSuggested strategy:\n• Keep only what you need for daily use in a hot wallet\n• Store long-term capital in a cold wallet\n• Never keep large amounts on an exchange; \"not your keys, not your coins\"\n\nNote: with a hardware device, record the recovery phrase yourself only. Buy the device from official sealed sources, not second-hand from unknown sellers."
  },
  {
    id: "a17", topic: "security",
    titleFa: "راستی‌آزمایی آدرس قرارداد",
    titleEn: "Verifying Contract Addresses",
    bodyFa: "در دنیای کریپتو، کلاهبرداران توکن‌های جعلی با نام و نماد مشابه توکن‌های معروف می‌سازند تا خریداران بی‌تجربه را فریب دهند. تنها راه مطمئن، راستی‌آزمایی آدرس قرارداد است.\n\nقبل از خرید یا اعتماد به یک توکن:\n• آدرس قرارداد را فقط از وب‌سایت رسمی پروژه، مستندات (Docs) و حساب‌های تأییدشده کپی کنید\n• در مرورگر بلاک‌چین (مثل Polygonscan) آدرس را جستجو کنید\n• حجم نقدینگی، تعداد هولدرها، سن قرارداد و کد تأییدشده (Verified) را بررسی کنید\n• تاریخچه تیم و جامعه را ببینید؛ پروژه واقعی سابقه شفاف دارد\n\nعلائم هشدار:\n• قراردادی که تازه ساخته شده و کدش تأیید نشده\n• نقدینگی کم و قفل نشده (ممکن است برداشته شود)\n• توکنی که فقط در چند صرافی کوچک و مشکوک لیست شده\n• نام و نمادی که یک حرف با توکن معروف تفاوت دارد\n\nقانون ساده: «آدرس فقط از منبع رسمی». اگر آدرسی را در پیام، کامنت یا جستجوی گوگل دیدید، قبل از استفاده از منبع رسمی چک کنید.",
    bodyEn: "In the crypto world, scammers create fake tokens with names and symbols similar to well-known ones to deceive inexperienced buyers. The only reliable way is verifying the contract address.\n\nBefore buying or trusting a token:\n• Copy the contract address only from the project's official website, documentation, and verified accounts\n• Search the address on a block explorer (such as Polygonscan)\n• Check liquidity volume, holder count, contract age, and verified source code\n• Look at the team and community history; a real project has a transparent track record\n\nWarning signs:\n• A freshly created contract with unverified code\n• Low, unlocked liquidity (it can be pulled)\n• A token listed only on a few small, suspicious exchanges\n• A name or symbol differing from a famous token by one letter\n\nThe simple rule: \"address only from official sources.\" If you see an address in a message, comment, or Google search, verify it from the official source before use."
  },
  {
    id: "a18", topic: "security",
    titleFa: "پشتیبان‌گیری و بازیابی امن کیف پول",
    titleEn: "Safe Backup and Recovery",
    bodyFa: "قوی‌ترین کیف پول هم بدون پشتیبان‌گیری درست، خطرناک است. اگر گوشی خراب شود، رایانه از کار بیفتد یا کیف پول پاک شود، تنها راه برگشت، عبارت بازیابی است.\n\nاصول پشتیبان‌گیری:\n• عبارت بازیابی را روی کاغذ بنویسید؛ ترتیب کلمات دقیقاً همان‌طور باشد\n• چند نسخه در مکان‌های مختلف (خانه، محل کار، محل مطمئن دیگر) نگهداری کنید\n• از کاغذ مقاوم و کیف پلاستیکی ضدآب استفاده کنید\n• هرگز نسخه دیجیتال (فایل، ایمیل، اسکرین‌شات) نسازید\n\nبازیابی امن:\n• کیف پول را فقط روی دستگاه امن و از برنامه رسمی بازسازی کنید\n• بعد از بازسازی، یک تراکنش آزمایشی کوچک بفرستید تا مطمئن شوید درست است\n• اگر عبارت را جایی لو دادید، بلافاصله دارایی را به کیف پول جدید و کاملاً تازه منتقل کنید\n\nنکته مهم: اگر کلید خصوصی را روی کاغذ می‌نویسید، آن را با قفل‌های رمزدار یا جای مخفی نگه دارید. پشتیبان‌گیری یعنی آرامش؛ هر چند ماه یک بار تست کنید که با عبارت می‌توانید کیف پول را باز کنید.",
    bodyEn: "Even the strongest wallet is dangerous without proper backup. If your phone breaks, your computer fails, or the wallet is wiped, the recovery phrase is the only way back.\n\nBackup principles:\n• Write the recovery phrase on paper with the words in the exact order\n• Keep several copies in different places (home, workplace, another safe location)\n• Use durable paper and a waterproof plastic pouch\n• Never create a digital copy (file, email, screenshot)\n\nSafe recovery:\n• Restore the wallet only on a secure device and from the official app\n• After restoring, send a small test transaction to confirm it works\n• If your phrase was ever exposed, immediately move funds to a brand-new wallet\n\nImportant: if you write the private key on paper, store it under a password lock or hidden place. Backup means peace of mind; every few months, test that you can open the wallet with the phrase."
  },
  {
    id: "a19", topic: "market",
    titleFa: "کاربردهای روزمره رمزارز",
    titleEn: "Everyday Crypto Use Cases",
    bodyFa: "بسیاری از مردم رمزارز را فقط برای سود و قیمت می‌شناسند، اما کاربردهای واقعی و روزمره آن در حال رشد است:\n\n• پرداخت کالا و خدمات: هزاران فروشگاه آنلاین و آفلاین رمزارز می‌پذیرند\n• حواله بین‌المللی: ارسال پول به خانواده در کشور دیگر با هزینه کم و سرعت بالا\n• خرید محتوا و اشتراک: پرداخت برای سرویس‌ها بدون نیاز به کارت بانکی\n• صدقه و خیریه: نهادهای خیریه رمزارز می‌پذیرند و هزینه کمتری صرف می‌شود\n• ایجاد دارایی: ساخت توکن برای کسب‌وکار، باشگاه، محتوا یا جامعه\n\nمزیت مهم رمزارز برای کسب‌وکارها: دریافت مستقیم از مشتری در هر نقطه دنیا، بدون واسطه بانکی و با کارمزد کم.\n\nنکته اسلامی: استفاده از رمزارز برای مبادله کالا و خدمت واقعی (دادوستد) کاملاً در چارچوب «تجارت حلال» است؛ به شرط آنکه کالا حلال باشد و معامله بدون ربا و فریب انجام شود. آنچه حرام است، استفاده از رمزارز در قمار، ربا یا فریب است، نه خود فناوری.",
    bodyEn: "Many people know crypto only for profit and price, but its real, everyday uses are growing:\n\n• Paying for goods and services: thousands of online and offline shops accept crypto\n• International remittances: sending money to family abroad with low cost and high speed\n• Buying content and subscriptions: paying for services without a bank card\n• Charity: charities accept crypto, and less is spent on fees\n• Creating assets: building a token for a business, club, content, or community\n\nAn important benefit of crypto for businesses: receiving direct payments from customers anywhere in the world, without banking intermediaries and with low fees.\n\nIslamic note: using crypto to exchange real goods and services (trade) fits perfectly within \"halal trade,\" provided the goods are halal and the transaction is free of riba and deception. What is forbidden is using crypto in gambling, riba, or deception — not the technology itself."
  },
  {
    id: "a20", topic: "market",
    titleFa: "بلاک‌چین و زنجیره تأمین",
    titleEn: "Blockchain and Supply Chains",
    bodyFa: "زنجیره تأمین، مسیر حرکت یک محصول از تولیدکننده تا مصرف‌کننده است. در زنجیره‌های سنتی، اطلاعات در سیستم‌های پراکنده نگهداری می‌شود و تأیید اصالت و منشأ کالا سخت و پرهزینه است.\n\nبلاک‌چین این مشکل را حل می‌کند: هر مرحله از مسیر کالا (تولید، بسته‌بندی، حمل، انبار) به‌صورت یک رکورد ثبت می‌شود که قابل تغییر نیست. مصرف‌کننده می‌تواند با اسکن یک کد، کل مسیر کالا را ببیند.\n\nمزایا:\n• شفافیت کامل: هیچ مرحله‌ای قابل پنهان‌کاری نیست\n• جلوگیری از تقلب: کالای تقلبی با تاریخچه‌ی جعلی قابل شناسایی است\n• کاهش هزینه: نیازی به نهادهای تأیید گران نیست\n\nاین کاربرد برای صنایع غذایی، دارویی و پوشاک بسیار مهم است؛ مثلاً می‌توان تأیید کرد که گوشت حلال از کشتارگاه مورد تأیید آمده است.\n\nنکته: شفافیت یکی از ارزش‌های اصلی اقتصاد اسلامی است. اسلامی که راست‌گویی در معامله را سفارش کرده، با فناوری‌ای که فریب را دشوار می‌کند، هم‌سو است.",
    bodyEn: "The supply chain is a product's journey from producer to consumer. In traditional chains, information is scattered across systems, and verifying authenticity and origin is hard and costly.\n\nBlockchain solves this: each stage of a product's journey (production, packaging, shipping, warehousing) is recorded as an immutable entry. A consumer can scan a code and see the entire journey.\n\nBenefits:\n• Full transparency: nothing can be hidden\n• Fraud prevention: counterfeit goods with fake histories can be detected\n• Lower costs: no need for expensive verification bodies\n\nThis use case matters greatly for food, medicine, and clothing industries — for example, verifying that halal meat comes from an approved slaughterhouse.\n\nNote: transparency is a core value of the Islamic economy. An Islam that commands truthfulness in trade is aligned with technology that makes deception difficult."
  },
  {
    id: "a21", topic: "market",
    titleFa: "توکن‌های غیرمثلی (NFT)",
    titleEn: "Non-Fungible Tokens (NFTs)",
    bodyFa: "NFT (توکن غیرمثلی) سند دیجیتالی است که مالکیت یک دارایی منحصربه‌فرد را نشان می‌دهد؛ مثل اثر هنری، کلکسیون، موسیقی یا حتی یک زمین مجازی. «غیرمثلی» یعنی هر کدام منحصربه‌فرد است و با دیگری قابل جابه‌جایی نیست.\n\nکاربردهای سالم NFT:\n• ثبت مالکیت اثر هنری دیجیتال برای هنرمند\n• فروش مستقیم آثار بدون واسطه‌های گران\n• بلیت رویدادها با قابلیت احراز اصالت\n• ثبت اسناد و گواهی‌ها\n\nمشکلاتی که باید بشناسید:\n• بسیاری از NFTها با تبلیغات اغراق‌آمیز و قیمت‌سازی فروخته می‌شوند — این می‌تواند نوعی فریب باشد\n• خرید برای «سود سریع» می‌تواند به قمار شبیه باشد\n• نقض حق کپی‌رایت در برخی پروژه‌ها\n\nنکته اسلامی: مالکیت اثر هنری یا کار فکری با سند شفاف، مشروع است. اما هر معامله‌ای که ابهام (غرر) شدید، فریب یا شرط‌بندی داشته باشد، اشکال شرعی دارد. اگر NFT را برای ارزش واقعی اثر بخرید، کار درستی کرده‌اید؛ اگر فقط برای «گران‌تر شدن» می‌خرید، با احتیاط رفتار کنید.",
    bodyEn: "An NFT (Non-Fungible Token) is a digital certificate that shows ownership of a unique asset — such as artwork, collectibles, music, or even virtual land. \"Non-fungible\" means each one is unique and cannot be exchanged one-for-one with another.\n\nHealthy NFT use cases:\n• Registering digital art ownership for artists\n• Selling works directly without costly intermediaries\n• Event tickets with authenticity verification\n• Registering documents and certificates\n\nProblems you should know:\n• Many NFTs are sold with exaggerated promotion and price manipulation — this can be deception\n• Buying for \"quick profit\" can resemble gambling\n• Copyright infringement in some projects\n\nIslamic note: owning artwork or intellectual work with a transparent certificate is legitimate. But any transaction with severe ambiguity (gharar), deception, or betting has religious problems. If you buy an NFT for the real value of the work, you are doing something right; if you buy only so it \"becomes more expensive,\" proceed with caution."
  },
  {
    id: "a22", topic: "market",
    titleFa: "هویت دیجیتال غیرمتمرکز",
    titleEn: "Decentralized Digital Identity",
    bodyFa: "هویت دیجیتال غیرمتمرکز یعنی اینکه شما خودتان کنترل داده‌های هویتی‌تان (نام، مدرک، مدرک تحصیلی، سابقه کاری) را در دست داشته باشید، نه یک شرکت یا دولت. به جای اعتماد به واسطه، اعتبار شما با امضای رمزنگاری‌شده تأیید می‌شود.\n\nمزایا:\n• حریم خصوصی: شما تصمیم می‌گیرید چه داده‌ای را با چه کسی به اشتراک بگذارید\n• امنیت: یک پایگاه داده مرکزی وجود ندارد که هک شود\n• قابلیت حمل: هویت شما بین همه خدمات قابل استفاده است\n\nکاربردها: ورود به خدمات مالی، تأیید مدارک تحصیلی، رأی‌گیری امن، تأیید اعتبار تجاری.\n\nنکته اسلامی: محافظت از اسرار و رازداری در اسلام سفارش شده و حریم خصوصی حق انسان است. فناوری‌ای که به فرد کنترل بیشتری بر داده‌هایش می‌دهد، با این ارزش هم‌سو است. البته باید مراقب بود که ناشناس بودن در حدی به کار نرود که زمینه فریب، فرار از مسئولیت یا پول‌شویی شود؛ مسئولیت‌پذیری هم بخشی از عدالت است.",
    bodyEn: "Decentralized digital identity means you control your identity data (name, documents, diplomas, work history) yourself, not a company or government. Instead of trusting an intermediary, your credentials are verified by cryptographic signature.\n\nBenefits:\n• Privacy: you decide what data to share with whom\n• Security: there is no central database to hack\n• Portability: your identity works across all services\n\nUse cases: access to financial services, verifying diplomas, secure voting, business credibility.\n\nIslamic note: Islam commands the protection of secrets, and privacy is a human right. Technology that gives individuals more control over their data aligns with this value. Of course, anonymity must not be used to enable deception, evasion of responsibility, or money laundering; accountability is also part of justice."
  },
  {
    id: "a23", topic: "market",
    titleFa: "حواله‌های بین‌المللی با رمزارز",
    titleEn: "Cross-Border Remittances with Crypto",
    bodyFa: "هزاران کارگر مهاجر هر ماه بخشی از درآمد خود را برای خانواده‌شان به کشورشان می‌فرستند. مسیرهای سنتی حواله چند روز طول می‌کشد و کارمزد بالا (گاهی ۷ تا ۱۰ درصد) می‌گیرد.\n\nرمزارز این مسیر را متحول می‌کند:\n• سرعت: انتقال در چند دقیقه به جای چند روز\n• هزینه: کارمزد بسیار کم، حتی برای مبالغ کوچک\n• دسترسی: فقط نیاز به یک کیف پول دارید، بدون حساب بانکی\n\nفرایند: خرید رمزارز در کشور مبدأ → انتقال به کیف پول دریافت‌کننده → تبدیل به پول محلی در کشور مقصد.\n\nاین کاربرد یکی از ارزشمندترین کاربردهای انسانی رمزارز است؛ پولی که واقعاً به خانواده‌های نیازمند می‌رسد و در جیب واسطه‌ها نمی‌ماند.\n\nنکته: از سرویس‌های دارای مجوز و قانونی برای تبدیل پول استفاده کنید و از مسیرهای غیرقانونی که می‌تواند شما را درگیر پول‌شویی کند پرهیز کنید. کمک به خانواده با مال حلال، از بهترین صدقه‌هاست.",
    bodyEn: "Thousands of migrant workers send part of their income home every month. Traditional remittance routes take days and charge high fees (sometimes 7 to 10 percent).\n\nCrypto transforms this route:\n• Speed: transfers in minutes instead of days\n• Cost: very low fees, even for small amounts\n• Access: all you need is a wallet, no bank account\n\nThe process: buy crypto in the origin country, transfer to the recipient's wallet, then convert to local currency in the destination country.\n\nThis is one of the most valuable, human uses of crypto: money that genuinely reaches needy families instead of staying in intermediaries' pockets.\n\nNote: use licensed and legal services for conversion and avoid illegal routes that can involve you in money laundering. Helping family with halal wealth is among the best forms of charity."
  },
  {
    id: "a24", topic: "market",
    titleFa: "مرور اخبار بازار (هفتگی)",
    titleEn: "Weekly Market News Roundup",
    bodyFa: "در این بخش، هر هفته تحولات مهم بازار را به‌صورت اطلاع‌رسانی مرور می‌کنیم؛ بدون دعوت به خرید و فروش عجولانه، فقط برای آگاهی شما.\n\nاین هفته چه چیزهایی مهم بود:\n• شبکه‌های بزرگ بلاک‌چین به‌روزرسانی‌هایی برای کاهش کارمزد و افزایش سرعت منتشر کردند\n• چند کشور در حال بررسی قوانین شفاف‌تر برای رمزارز هستند؛ قانون‌گذاری شفاف، امنیت بیشتری برای کاربران می‌آورد\n• آمار پذیرش رمزارز توسط کسب‌وکارهای کوچک همچنان در حال رشد است\n\nنکته‌هایی برای هفته آینده:\n• اخبار را از منابع رسمی و متعدد دنبال کنید، نه از شایعات شبکه‌های اجتماعی\n• تحولات قانونی هر کشور را پیگیری کنید؛ آن‌ها بر بازار اثر واقعی دارند\n• قبل از هر تصمیم، وضعیت کلان بازار و اخبار پروژه‌ای که دنبال می‌کنید را بررسی کنید\n\nیادآوری: اخبار ابزار آگاهی‌اند، نه دلیل عجله. بازار کریپتو پرنوسان است و خبر خوب یا بد نباید شما را به تصمیم شتاب‌زده وادار کند. تصمیم آگاهانه و آرام، همیشه بهتر از واکنش هیجانی است.",
    bodyEn: "In this section we review the week's important market developments as information only — without urging hasty buying or selling, purely for your awareness.\n\nWhat mattered this week:\n• Major blockchain networks released upgrades to lower fees and increase speed\n• Several countries are exploring clearer crypto regulations; transparent legislation brings more security for users\n• Adoption of crypto by small businesses continues to grow\n\nTips for next week:\n• Follow news from official and multiple sources, not social media rumors\n• Track legal developments in each country; they have a real impact on the market\n• Before any decision, review the overall market conditions and the news of the project you follow\n\nReminder: news is a tool for awareness, not a reason to rush. The crypto market is volatile, and good or bad news should not push you into hasty decisions. A calm, informed decision is always better than an emotional reaction."
  },
  {
    id: "a25", topic: "mining",
    titleFa: "ماینینگ چیست؟",
    titleEn: "What is Mining?",
    bodyFa: "ماینینگ (استخراج) فرایندی است که در آن رایانه‌های قدرتمند برای تأیید تراکنش‌ها و تولید بلاک جدید در بلاک‌چین با یکدیگر رقابت می‌کنند. ماینری که بتواند مسئله ریاضی را حل کند، بلاک را ثبت و در ازای آن پاداش شبکه دریافت می‌کند.\n\nچرا ماینینگ لازم است؟\n• تأیید تراکنش‌ها: اطمینان از اینکه پول دو بار خرج نشده است\n• امنیت شبکه: هرچه ماینرهای بیشتری مشارکت کنند، حمله به شبکه سخت‌تر می‌شود\n• توزیع عادلانه‌تر: پاداش به کسانی می‌رسد که واقعاً کار کرده‌اند\n\nماینینگ در شبکه‌های اثبات کار (Proof of Work) مثل بیت‌کوین انجام می‌شود. شبکه‌هایی مثل Polygon از روش دیگری به نام اثبات سهام استفاده می‌کنند که انرژی بسیار کمتری مصرف می‌کند.\n\nنکته: ماینینگ یک کسب‌وکار است، نه یک بازی شانسی. ورود به آن نیازمند محاسبه دقیق هزینه برق، تجهیزات و نگهداری است. کسانی که «ماینینگ با سود تضمینی» تبلیغ می‌کنند، معمولاً کلاهبردارند.",
    bodyEn: "Mining is the process in which powerful computers compete to validate transactions and produce new blocks on a blockchain. The miner who solves the mathematical puzzle records the block and receives a network reward.\n\nWhy is mining necessary?\n• Validating transactions: ensuring money is not spent twice\n• Network security: the more miners participate, the harder it is to attack the network\n• Fairer distribution: rewards go to those who actually did the work\n\nMining happens on Proof-of-Work networks such as Bitcoin. Networks like Polygon use a different method called Proof of Stake, which consumes far less energy.\n\nNote: mining is a business, not a game of chance. Entering it requires careful calculation of electricity, equipment, and maintenance costs. Those advertising \"mining with guaranteed profit\" are usually scammers."
  },
  {
    id: "a26", topic: "mining",
    titleFa: "ماینینگ به عنوان شغل حلال",
    titleEn: "Mining as a Halal Profession",
    bodyFa: "ماینینگ به این دلیل که مبتنی بر «کار و تلاش واقعی» است (صرف برق، سرمایه‌گذاری، نگهداری تجهیزات، تأیید تراکنش‌ها) از نظر بسیاری از علما یک فعالیت حلال است، به شرط اینکه منابع اولیه حلال باشد و درآمد آن شفاف باشد.\n\nویژگی‌های یک ماینر حلال و موفق:\n• سرمایه‌گذاری با پول حلال و بدون وام ربوی\n• پرداخت به‌موقع برق و مالیات\n• رعایت امانت‌داری در قراردادها (مثلاً استخرهای ماینینگ)\n• دانش کافی از فناوری و محاسبه هزینه‌ها\n• صبر و دید بلندمدت؛ نه انتظار سود افسانه‌ای\n\nنکته احتیاطی: برخی علما درباره مصرف انرژی و تأثیر زیست‌محیطی احتیاط دارند. اگر در کشور شما نظر رسمی نهاد فقهی وجود دارد، حتماً از آن پیروی کنید.\n\nتأمل: هر کسب‌وکار حلالی، اگر همراه با صداقت و مسئولیت‌پذیری باشد، هم برکت دارد و هم ماندگار است. ماینینگ هم یک کسب‌وکار واقعی است که شایسته است با همان جدیت اداره شود.",
    bodyEn: "Mining, because it is based on \"real work and effort\" (consuming electricity, investing, maintaining equipment, validating transactions), is considered a halal activity by many scholars — provided the initial resources are halal and income is transparent.\n\nQualities of a halal and successful miner:\n• Investing halal money, without riba-based loans\n• Paying electricity and taxes on time\n• Honesty in contracts (for example, mining pools)\n• Enough knowledge of the technology and cost calculation\n• Patience and a long-term view; no expectation of mythical profits\n\nA caution: some scholars are cautious about energy consumption and environmental impact. If your country's fiqh institution has an official view, be sure to follow it.\n\nReflection: every halal business, when run with honesty and responsibility, is both blessed and lasting. Mining is a real business that deserves to be run with the same seriousness."
  },
  {
    id: "a27", topic: "mining",
    titleFa: "سخت‌افزار مورد نیاز ماینینگ",
    titleEn: "Mining Hardware Essentials",
    bodyFa: "ماینینگ بدون سخت‌افزار مناسب ممکن نیست. انتخاب تجهیزات مهم‌ترین تصمیم مالی در این کسب‌وکار است:\n\n• دستگاه‌های تخصصی (ASIC): برای ماینینگ بیت‌کوین طراحی شده‌اند و کارایی بالایی دارند اما گران‌اند\n• کارت‌های گرافیک (GPU): برای ماینینگ ارزهای مبتنی بر اتریوم کلاسیک و دیگر کوین‌ها مناسب‌اند\n• منبع تغذیه با کیفیت: قلب دستگاه شما؛ ارزان خریدن آن یعنی ریسک آتش‌سوزی\n• تهویه و خنک‌سازی: گرما بزرگ‌ترین دشمن سخت‌افزار است\n• اتصال اینترنت پایدار: قطعی‌ها یعنی از دست دادن زمان استخراج\n\nقبل از خرید:\n• بازدهی و مصرف برق هر دستگاه را مقایسه کنید\n• هزینه برق منطقه خود را در نظر بگیرید؛ برق گران یعنی سود کم یا ضرر\n• از فروشندگان معتبر بخرید؛ دستگاه دست‌ساز یا دست دوم ممکن است مشکل داشته باشد\n\nقانون طلایی: هیچ وقت برای خرید تجهیزات با پولی که توان از دست دادنش را ندارید یا با وام ربوی اقدام نکنید. در کسب‌وکار حلال، ریسک باید معقول و محاسبه‌شده باشد.",
    bodyEn: "Mining is impossible without proper hardware. Choosing equipment is the most important financial decision in this business:\n\n• Specialized devices (ASICs): designed for Bitcoin mining, highly efficient but expensive\n• Graphics cards (GPUs): suitable for mining Ethereum Classic-based coins and others\n• A quality power supply: the heart of your rig; buying cheap means fire risk\n• Ventilation and cooling: heat is hardware's biggest enemy\n• Stable internet connection: outages mean lost mining time\n\nBefore buying:\n• Compare each device's efficiency and power draw\n• Consider your local electricity cost; expensive power means low profit or loss\n• Buy from reputable sellers; homemade or used devices may have issues\n\nThe golden rule: never buy equipment with money you cannot afford to lose or with a riba-based loan. In a halal business, risk must be reasonable and calculated."
  },
  {
    id: "a28", topic: "mining",
    titleFa: "مصرف انرژی و بهره‌وری در ماینینگ",
    titleEn: "Energy Consumption and Efficiency in Mining",
    bodyFa: "ماینینگ به برق زیادی نیاز دارد و مصرف انرژی یکی از مهم‌ترین بحث‌های این صنعت است. هم از نظر اقتصادی و هم از نظر شرعی، بهره‌وری انرژی اهمیت دارد.\n\nچرا بهره‌وری مهم است:\n• برق معمولاً بزرگ‌ترین هزینه جاری ماینر است؛ اگر مصرف بالا باشد، سود از بین می‌رود\n• استفاده بهینه از انرژی، هم از اسراف جلوگیری می‌کند و هم اثر زیست‌محیطی را کاهش می‌دهد\n• در شرایط قطعی برق، شهرت منفی صنعت ماینینگ را بیشتر می‌کند\n\nراه‌های افزایش بهره‌وری:\n• انتخاب دستگاه‌هایی با نسبت بازدهی به مصرف بهتر\n• مدیریت حرارت با تهویه مناسب (گرمای بیش از حد مصرف را بالا می‌برد)\n• استفاده از برق در ساعت‌های کم‌بار (اگر تعرفه پلکانی است)\n• در نظر گرفتن منابع انرژی تجدیدپذیر در مناطق مناسب\n\nنکته اسلامی: قرآن به اسراف نهی کرده است. ماینری که به فکر بهره‌وری و محیط زیست است، علاوه بر سود اقتصادی، مسئولیت اجتماعی خود را هم انجام می‌دهد. کسب حلال وقتی ارزشمندتر است که به جامعه و طبیعت آسیب نزند.",
    bodyEn: "Mining requires a lot of electricity, and energy consumption is one of the industry's biggest debates. Both economically and religiously, energy efficiency matters.\n\nWhy efficiency matters:\n• Electricity is usually a miner's largest running cost; high consumption kills profit\n• Using energy efficiently both prevents waste and reduces environmental impact\n• During power shortages, it worsens mining's negative reputation\n\nWays to improve efficiency:\n• Choose devices with a better efficiency-to-consumption ratio\n• Manage heat with proper ventilation (excess heat raises consumption)\n• Run at off-peak hours where tariffs are tiered\n• Consider renewable energy sources in suitable regions\n\nIslamic note: the Quran forbids waste. A miner who cares about efficiency and the environment does their social duty in addition to earning profit. Halal income is more valuable when it does not harm society and nature."
  },
  {
    id: "a29", topic: "mining",
    titleFa: "پاداش بلاک و امنیت شبکه",
    titleEn: "Block Rewards and Network Security",
    bodyFa: "هر بار که ماینری بلاک جدید تولید می‌کند، پاداشی دریافت می‌کند: مقداری سکه تازه + کارمزد تراکنش‌های آن بلاک. این پاداش چرخه حیات بلاک‌چین است.\n\nپاداش چه نقشی دارد؟\n• انگیزه: ماینرها فقط برای پاداش، انرژی و سرمایه صرف می‌کنند\n• امنیت: هرچه پاداش و سود ماینینگ متعادل‌تر باشد، شبکه پایدارتر و حمله به آن سخت‌تر است\n• توزیع: پاداش به کسانی می‌رسد که واقعاً کار کرده‌اند\n\nدر شبکه بیت‌کوین، پاداش هر چهار سال نصف می‌شود (هالوینگ). این کاهش پاداش، عرضه را محدود و کمیاب می‌کند.\n\nنکته اقتصادی: درک چرخه پاداش به شما کمک می‌کند دیدگاه واقع‌بینانه‌ای به ماینینگ داشته باشید. سود ماینینگ ثابت نیست؛ به قیمت ارز، سختی شبکه، پاداش و هزینه برق بستگی دارد.\n\nنکته اخلاقی: ماینری که با صداقت به شبکه خدمت می‌کند، امنیت یک سیستم مشترک را تضمین می‌کند. این کار، نوعی «خدمت به جامعه» است که در اسلام ارزش والایی دارد.",
    bodyEn: "Each time a miner produces a new block, they receive a reward: newly minted coins plus the transaction fees of that block. This reward is the lifeblood of a blockchain.\n\nWhat role does the reward play?\n• Incentive: miners only spend energy and capital for the reward\n• Security: the more balanced mining profit is, the more stable the network and the harder to attack\n• Distribution: rewards go to those who actually did the work\n\nOn Bitcoin, the reward halves every four years (halving). This reduction keeps supply limited and scarce.\n\nEconomic note: understanding the reward cycle gives you a realistic view of mining. Mining profit is not fixed; it depends on coin price, network difficulty, the reward, and electricity cost.\n\nEthical note: a miner who honestly serves the network secures a shared system. This is a form of \"service to the community,\" which holds great value in Islam."
  },
  {
    id: "a30", topic: "mining",
    titleFa: "استخرهای ماینینگ",
    titleEn: "Mining Pools",
    bodyFa: "وقتی یک ماینر به‌تنهایی کار می‌کند، شانس پیدا کردن بلاک بسیار کم و نامنظم است. استخر ماینینگ (Pool) راه حل این مشکل است: ماینرها قدرت محاسباتی خود را کنار هم می‌گذارند و پاداش هر بلاک را به نسبت مشارکت هرکس تقسیم می‌کنند.\n\nمزایا:\n• درآمد منظم‌تر: به‌جای سودهای گهگاه و نامنظم، درآمد کوچک و مستمر\n• کاهش ریسک: شانس پیدا کردن بلاک به‌صورت گروهی تقسیم می‌شود\n• دسترسی آسان: برای ماینرهای کوچک بدون تجهیزات عظیم ممکن است\n\nنکاتی که باید بررسی کنید:\n• شهرت و شفافیت استخر؛ سابقه پرداخت‌های منظم\n• درصد کارمزد استخر از پاداش\n• حداقل مبلغ برداشت و روش پرداخت\n• شفافیت قرارداد: تقسیم پاداش باید منصفانه و مشخص باشد\n\nنکته شرعی: مشارکت در استخر شبیه «شراکت» (مشارکت) است که در اسلام جایز است، به شرط آنکه شرایط تقسیم سود و زیان از ابتدا شفاف باشد و هیچ طرفی ظلم نشود. قرارداد مبهم (غرر) یا شرطی که یک طرف را فریب دهد، مشکل شرعی دارد.",
    bodyEn: "When a miner works alone, the chance of finding a block is tiny and irregular. A mining pool solves this: miners combine their computing power and divide each block's reward in proportion to each member's contribution.\n\nBenefits:\n• More regular income: small, steady earnings instead of occasional, irregular windfalls\n• Reduced risk: the chance of finding a block is shared collectively\n• Accessibility: possible for small miners without massive equipment\n\nThings to check:\n• The pool's reputation and transparency; a history of regular payouts\n• The pool's fee percentage on rewards\n• Minimum withdrawal amount and payment method\n• Contract transparency: reward division must be fair and clearly defined\n\nReligious note: joining a pool resembles partnership (musharakah), which is permissible in Islam, provided the terms of profit and loss sharing are clear from the start and no party is wronged. A vague contract (gharar) or a term that deceives one party has religious problems."
  },
];

